# Generated by Django 5.1.1 on 2024-09-13 19:30

import django.db.models.deletion
import test_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_product.attr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attrs',
            field=models.ManyToManyField(through='test_product.ProductAttr', to='test_product.attr'),
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_product.productattr')),
                ('product', test_product.models.CustomForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unique_products', to='test_product.product')),
            ],
        ),
    ]
